name: npm publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install --immutable
      - name: 'set environments'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          git config --global user.email "sha.sdk_deployment@sendbird.com"
          git config --global user.name "sendbird-sdk-deployment"
      - name: 'publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release-it ${{ github.event.inputs.version }} --ci
